databases:
  - name: ai-agent-db
    plan: free

services:
  - type: web
    name: ai-agent-app
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build   # ✅ INSTALL deps THEN build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ai-agent-db
          property: connectionString
      - key: PYTHON_PATH
        value: python3
